server:
  port: 7001
  servlet:
    context-path: /ad-search

spring:
  application:
    name: eureka-client-ad-search
  # jpa配置信息
  jpa:
    # 显示SQL语句
    show-sql: true
    hibernate:
      # 不去操作表(5种选项)
      ddl-auto: none
    properties:
      # SQL语句格式化
      hibernate.format_sql: true
    # 懒加载相关的 怕出现bean装配找不到的问题 所以设置为false
    open-in-view: false
  datasource:
    # 数据库名称是 imooc_ad_data
    url: jdbc:mysql://192.168.169.129:3306/imooc_ad_data?autoReconnect=true
    username: root
    password: yijialu7
    # 数据库连接池配置
#    tomcat:
#      max-active: 4
#      min-idle: 2
#      initial-size: 2

eureka:
  client:
    service-url:
      defaultZone: http://server1:8000/eureka

# 开启断路器功能
feign:
  hystrix:
    enabled: true

# 开启服务监控功能 且暴露所有监控端点
management:
  endpoints:
    web:
      exposure:
        include: "*"

# binlog监听的配置信息
adconf:
  mysql:
    host: 192.168.169.129
    port: 3306
    username: root
    password: yijialu7
    binlogName: ""
    position: -1
  kafka:
    topic: ad-search-mysql-data