
-- 广告投放用户表
CREATE TABLE ad_user(
  id BIGINT(20) PRIMARY KEY AUTO_INCREMENT COMMENT '自增主键',
  username VARCHAR(256) UNIQUE KEY NOT NULL DEFAULT '' COMMENT '用户名',
  token VARCHAR(256) NOT NULL DEFAULT '' COMMENT '按username生成的md5 token',
  user_status TINYINT(4) NOT NULL DEFAULT '0' COMMENT'用户状态',
  create_time DATETIME NOT NULL DEFAULT '2019-10-01 00:00:00' COMMENT '创建时间',
  update_time DATETIME NOT NULL DEFAULT '2019-10-01 00:00:00' COMMENT '修改时间'
) ENGINE=INNODB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COMMENT='用户信息表';


-- 推广计划表
CREATE TABLE ad_plan(
  id BIGINT(20) PRIMARY KEY AUTO_INCREMENT COMMENT '自增主键',
  user_id BIGINT(20) NOT NULL DEFAULT '0' COMMENT '推广计划所属用户',
  plan_name VARCHAR(48) NOT NULL COMMENT '推广计划名称',
  plan_status TINYINT(4) NOT NULL DEFAULT '0' COMMENT '推广计划状态',
  start_date DATETIME NOT NULL DEFAULT '2019-10-01 00:00:00' COMMENT '推广计划开始时间',
  end_date DATETIME NOT NULL DEFAULT '2019-10-01 00:00:00' COMMENT '推广计划结束时间',
  create_time DATETIME NOT NULL DEFAULT '2019-10-01 00:00:00' COMMENT '推广计划创建时间',
  update_time DATETIME NOT NULL DEFAULT '2019-10-01 00:00:00' COMMENT '推广计划修改时间'
) ENGINE=INNODB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COMMENT='推广计划表';


-- 推广单元表
CREATE TABLE ad_unit(
  id BIGINT(20) PRIMARY KEY AUTO_INCREMENT COMMENT '自增主键',
  plan_id BIGINT(20) NOT NULL DEFAULT '0' COMMENT '推广单元所属计划',
  unit_name VARCHAR(48) NOT NULL COMMENT '推广单元名称',
  unit_status TINYINT(4) NOT NULL DEFAULT '0' COMMENT '推广单元状态',
  position_type TINYINT(4) NOT NULL DEFAULT '0' COMMENT '广告展开位置类型 开屏、贴片、中贴、暂停贴等位置',
  budget BIGINT(20) NOT NULL DEFAULT '0' COMMENT '推广单元预算金额',
  create_time DATETIME NOT NULL DEFAULT '2019-10-01 00:00:00' COMMENT '推广单元创建时间',
  update_time DATETIME NOT NULL DEFAULT '2019-10-01 00:00:00' COMMENT '推广单元修改时间'
) ENGINE=INNODB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COMMENT='推广单元表';


-- 广告创意表
CREATE TABLE ad_creative(
  id BIGINT(20) PRIMARY KEY AUTO_INCREMENT COMMENT '自增主键',
  user_id BIGINT(20) NOT NULL DEFAULT '0' COMMENT '创意所属用户',
  NAME VARCHAR(48) NOT NULL COMMENT '广告创意名称',
  TYPE TINYINT(4) NOT NULL DEFAULT '0' COMMENT '广告创意类型，图片、视频、文本等类型',
  material_type TINYINT(4) NOT NULL DEFAULT '0' COMMENT '广告创意的物料类型 如图片有：jpg、png、bmp等',
  height TINYINT(10) NOT NULL DEFAULT '0' COMMENT '物料的高度',
  width TINYINT(10) NOT NULL DEFAULT '0' COMMENT '物料的宽度',
  size BIGINT(20) NOT NULL DEFAULT '0' COMMENT '物料的大小 kb、字节等',
  duration TINYINT(10) NOT NULL DEFAULT '0' COMMENT '物料的时长，视频不为0，其余为0',
  audit_status TINYINT(4) NOT NULL DEFAULT '0' COMMENT '物料的审核状态',
  url VARCHAR(512) NOT NULL COMMENT '物料的url信息',
  create_time DATETIME NOT NULL DEFAULT '2019-10-01 00:00:00' COMMENT '创意创建时间',
  update_time DATETIME NOT NULL DEFAULT '2019-10-01 00:00:00' COMMENT '创意修改时间'
) ENGINE=INNODB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COMMENT='广告创意表';


-- 广告单元の关键词表
CREATE TABLE ad_unit_keyword(
  id BIGINT(20) PRIMARY KEY AUTO_INCREMENT COMMENT '自增主键',
  unit_id BIGINT(20) NOT NULL DEFAULT '0' COMMENT '所属推广单元',
  keyword VARCHAR(128) NOT NULL COMMENT '关键词'
) ENGINE=INNODB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COMMENT='广告单元の关键词表';


-- 广告单元の兴趣标签表
CREATE TABLE ad_unit_it(
  id BIGINT(20) PRIMARY KEY AUTO_INCREMENT COMMENT '自增主键',
  unit_id BIGINT(20) NOT NULL DEFAULT '0' COMMENT '所属推广单元',
  it_tag VARCHAR(128) NOT NULL COMMENT '兴趣标签'
) ENGINE=INNODB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COMMENT='广告单元の兴趣标签表';


-- 广告单元の推广地域表
CREATE TABLE ad_unit_district(
  id BIGINT(20) PRIMARY KEY AUTO_INCREMENT COMMENT '自增主键',
  unit_id BIGINT(20) NOT NULL DEFAULT '0' COMMENT '所属推广单元',
  province VARCHAR(64) NOT NULL COMMENT '推广省份',
  city VARCHAR(128) NOT NULL COMMENT '推广城市'
) ENGINE=INNODB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COMMENT='广告单元の推广地域表';


-- 广告单元与创意中间表
CREATE TABLE creative_unit(
  id BIGINT(20) PRIMARY KEY AUTO_INCREMENT COMMENT '自增主键',
  creative_id BIGINT(20) NOT NULL DEFAULT '0' COMMENT '创意的id',
  unit_id BIGINT(20) NOT NULL DEFAULT '0' COMMENT '推广单元的id'
) ENGINE=INNODB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COMMENT='广告单元与创意中间表';


