spring:
  application:
    name: ag-gateway

server:
  port: 9000

# 将网关服务注册到eureka注册中心，实现请求分发
eureka:
  client:
    service-url:
      defaultZone: http://server1:8000/eureka/

zuul:
  # 要路由必须带的前缀
  prefix: /seven
  routes:
    # 服务的别名
    sponsor:
      # 带这个path就会转发到服务对应 /** 的controller方法下
      path: /ad-sponsor/**
      # 指定注册中心里的服务名称
      serviceId: eureka-client-ad-sponsor
      # 不跳过前缀 即保留 /ad-sponsor 这截信息
      strip-prefix: false
      # 例子：http://server1:9000/seven/ad-sponsor/user ——》 http://server1:7000/ad-sponsor/user