server:
  port: 7000
  servlet:
    context-path: /ad-sponsor

spring:
  application:
    name: eureka-client-ad-sponsor
  # jpa配置信息
  jpa:
    # 显示SQL语句
    show-sql: true
    hibernate:
      # 不去操作表(5种选项)
      ddl-auto: none
    properties:
      # SQL语句格式化
      hibernate.format_sql: true
    # 懒加载相关的 怕出现bean装配找不到的问题 所以设置为false
    open-in-view: false
  datasource:
    url: jdbc:mysql://192.168.169.129:3306/immoc_ad_data?autoReconnect=true
    username: root
    password: yijialu7
    # 数据库连接池配置
#    tomcat:
#      max-active: 4
#      min-idle: 2
#      initial-size: 2

eureka:
  client:
    service-url:
      defaultZone: http://server1:8000/eureka